package nwscore.ffrectmodel;

import com.google.gson.annotations.SerializedName;

public class ProviderRates{

	@SerializedName("FEDEX_2_DAY")
	private FEDEX2DAY fEDEX2DAY;

	@SerializedName("STANDARD_OVERNIGHT")
	private STANDARDOVERNIGHT sTANDARDOVERNIGHT;

	@SerializedName("FEDEX_GROUND")
	private FEDEXGROUND fEDEXGROUND;

	@SerializedName("INTERNATIONAL_ECONOMY")
	private INTERNATIONALECONOMY iNTERNATIONALECONOMY;

	public void setFEDEX2DAY(FEDEX2DAY fEDEX2DAY){
		this.fEDEX2DAY = fEDEX2DAY;
	}

	public FEDEX2DAY getFEDEX2DAY(){
		return fEDEX2DAY;
	}

	public void setSTANDARDOVERNIGHT(STANDARDOVERNIGHT sTANDARDOVERNIGHT){
		this.sTANDARDOVERNIGHT = sTANDARDOVERNIGHT;
	}

	public STANDARDOVERNIGHT getSTANDARDOVERNIGHT(){
		return sTANDARDOVERNIGHT;
	}

	public void setFEDEXGROUND(FEDEXGROUND fEDEXGROUND){
		this.fEDEXGROUND = fEDEXGROUND;
	}

	public FEDEXGROUND getFEDEXGROUND(){
		return fEDEXGROUND;
	}

	public void setINTERNATIONALECONOMY(INTERNATIONALECONOMY iNTERNATIONALECONOMY){
		this.iNTERNATIONALECONOMY = iNTERNATIONALECONOMY;
	}

	public INTERNATIONALECONOMY getINTERNATIONALECONOMY(){
		return iNTERNATIONALECONOMY;
	}
}