/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nwscore;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonParser;
import com.google.gson.stream.JsonReader;
import kong.unirest.HttpResponse;
import nwscore.graphql.DefaultGQLOrderService;
import nwscore.graphql.GQLOrderService;
import nwscore.graphql.GraphqlClient;
import nwscore.io.DefaultRestClient;
import nwscore.io.InvalidCredentialsException;

import java.io.FileReader;
import java.io.PrintWriter;
import java.time.LocalDateTime;

public class AppCreateGroups {
    public String getGreeting() {
        return "Hello world.";
    }


    public static void main(String[] args) throws Exception, InvalidCredentialsException {


  /*      NwsContext context = NwsContext.Builder
                .start()
                .withCredentials(new Credential("btashan@newstore.com", "bORA@911!s"))
                .withTenant("vince")
                .withEnvironment(NwsEnvironment.STAGING)
                .withNwsUrl("newstore.net")
                .build();

        DefaultRestClient client = new DefaultRestClient(context);
*/

        for (String s : locations) {
        //String s =  "V-FFL-5948-FASHIONOUTLET";
            String query = "{\n" +
                    "    \"group_name\": \"invfg-%1$s\",\n" +
                    "    \"fulfillment_nodes\": [\n" +
                    "        \"%1$s\"\n" +
                    "    ]\n" +
                    "}";


            query = "                        {\n" +
                    "                            \"fulfillment_node_id\": \"%s\",\n" +
                    "                            \"provider_rate\": \"FEDEX_GROUND\"\n" +
                    "                        },";
            String q = String.format(query, s);
            System.out.println(q);
            /*HttpResponse<String> response = client.post("/v0/d/availabilities/groups", q);
            if (response.isSuccess()) {
                System.out.println("Success");
            } else {
                System.out.println(response.getStatusText());
            }*/
        }

    }


    private static String [] locations = {
    //        "D100-PORTLG0100",
            "V-FFL-4834-MALIBUCNTRYMART",
            "V-FFL-4835-PRINCEST",
            "V-FFL-4836-GEARYST",
            "V-FFL-4837-HIGHLANDPARK",
            "V-FFL-4838-TOWNCENTER",
            "V-FFL-4840-THEWESTCHESTER",
            "V-FFL-4842-PHIPPSPLAZA",
            "V-FFL-4844-STANFORDCENTER",
            "V-FFL-4845-BELLEVUESQ",
            "V-FFL-4846-EASTOAKST",
            "V-FFL-4847-FASHIONISLAND",
            "V-FFL-4901-MADISONAVE",
            "V-FFL-5904-CABAZON",
            "V-FFL-4906-WESTPORT",
            "V-FFL-4907-GREENWICH",
            "V-FFL-4909-MERCER",
            "V-FFL-4910-COLUMBUSAVE",
            "V-FFL-5911-RIVERHEAD",
            "V-FFL-5912-SEATTLEOUTLET",
            "V-FFL-5913-LASVEGASOUTLET",
            "V-FFL-4915-NEWBURYST",
            "V-FFL-4917-CHESTNUTHILL",
            "V-FFL-4918-PASADENA",
            "V-FFL-4919-WALNUTST",
            "V-FFL-5920-SANMARCOS",
            "V-FFL-5921-CARLSBAD",
            "V-FFL-5922-WRENTHAM",
            "V-FFL-5923-CAMARILLO",
            "V-FFL-4924-BROOKFIELD",
            "V-FFL-4925-RIVEROAKS",
            "V-FFL-5926-SFPREMIUMOUTLETS",
            "V-FFL-5927-SAWGRASSMILLS",
            "V-FFL-4928-CITYCENTERDC",
            "V-FFL-4929-MERRICKPARK",
            "V-FFL-4930-ABBOTKINNEY",
            "V-FFL-4931-SCOTTSDALEQRT",
            "V-FFL-5932-CHICAGOPREMIUM",
            "V-FFL-5933-WOODBURYCOMMONS",
            "V-FFL-4934-FORUMSHOPS",
            "V-FFL-4935-TYSONSGALLERIA",
            "V-FFL-4936-KINGOFPRUSSIA",
            "V-FFL-4938-FASHIONVALLEY",
            "V-FFL-4939-THEGROVE",
            "V-FFL-4940-SOMERSET",
            "V-FFL-4941-INTLMARKETPLACE",
            "V-FFL-4942-MELROSE",
            "V-FFL-4943-ELPASEOVILLAGE",
            "V-FFL-4944-THEDOMAIN",
            "V-FFL-4945-SHORTHILLSMALL",
            "V-FFL-4946-WATERSIDESHOPS",
            "V-FFL-4947-PACIFICPALISADES",
            "V-FFL-5948-FASHIONOUTLET",
            "V-FFL-4955-PALMBEACHGARDENS",
            "V-FFL-4956-MALLATMILLENIA",
            "V-FFL-4958-FIFTHAVE",
            "V-FFL-4959-SANTANAROW",
            "V-FFL-4960-AVENTURA",
            "V-FFL-4961-RIVERSIDE",
            "V-FFL-5962-NATIONALHARBOR",
            "V-FFL-5963-ORLANDOVINE",
            "V-FFL-4971-EASTHAMPTON",
            "V-FFL-7630-DRAYCOTT"
    };


}
